### ISSUE TITLE
Registry Error - This registry does not appear to have a valid schema list - when using the base chromium example

### ISSUE THREAD

**Issue by GadgetGeekNI** [kasmtech/workspaces_registry_template#2]
Hi there,

When I get a schema error, would this generally indicate an error with a workspace.json file or could this be an issue with the js code?

I can't see any logs to help point me in the right direction unfortunately. 

I am using the basic Chromium example, completely unchanged to validate that that it should work as intended but getting the below error.

![image](https://github.com/kasmtech/workspaces_registry_template/assets/64256007/0456bb87-4d10-47e5-81bb-64813bc52956)

**Comment by KodeStar** [comment]
What is the url you are try to add? It's generally something it doesn't like with either the json file itself or the url you tried to import. If you copied the url from the address bar this is the error you would see as that's not a valid import url, if you clicked on the "Workspace Registry Link" and pasted that one, then you shouldn't see that error. 

The difference between the 2 is that the address bar has the current schema version (i.e. /1.0/) whereas the other one doesn't. This is because there can be multiple versions of the schema and kasm should install the version it's compatible with. 

If your issue was different let me know and I'll see if I can be any more help

**Comment by GadgetGeekNI** [comment]
Hi KodeStar, 

Thanks for getting back to me so quickly. 

Maybe that's where I'm going wrong. 
I'm actually trying to build this out in a dockerfile to be hosted in AWS ECS instead as my org doesn't use Github and we have proprietary software we want to install that we may not want to advertise in a public facing web host. The site itself is up and works fine but I just couldn't get Kasm to accept the JSON schema.

I have my basePath set to '' as my url is just https://sub.domain.example.com/ , but it sounds like I'm missing a step somewhere in the build process to publish a basePath. 

For your own reference, my build command is simply..

```
npm ci --prefix processing 
npm ci --prefix site

node processing
cp -a public/. process

npm run deploy --prefix site
cp -a process/. public/ # Have to run it again because the deploy wipes the file and folders out
rm -rf process
```

Hopefully when I get this working fully I'll be able to publish or offer it here as an alternative to solely github pages hosted registries!

**Comment by KodeStar** [comment]
Yes please let me know how you get on. Take a look at this - https://github.com/kasmtech/workspaces_registry_template/blob/1.0/build_all_branches.sh because you probably are missing some of the bits from there.

Basically, among other things, that generates a versions.txt that lets kasm know the versions the registry supports (currently this will just be 1.0)

*edit* If you drop it all into a `/1.0/` folder, update the basePath and drop a versions.txt into the root, that might be all you need to do to get it working

**Comment by GadgetGeekNI** [comment]
Hey! 

Thank you for the pointers in the right direction. The below is what I used to get it working.

```
#!/usr/bin/env sh

# NOTE: This is to build locally.
npm ci --prefix processing 
npm ci --prefix site

node processing
cp -a public/. process

npm run deploy --prefix site

# Move things around
mv public '1.0'
mkdir public
mv ./1.0 ./public/

# Setup root dir
cp -a process/. public/1.0/
echo '1.0' > public/versions.txt
echo '<meta http-equiv="refresh" content="0; url=./1.0/">' > public/index.html

# Cleanup
rm -rf process
```


Dockerfile is just as follows;

```

FROM nginx:alpine

COPY ./public /usr/share/nginx/html

# Expose the custom port
EXPOSE 80
```


I hope this helps others! 

I was able to run the build steps in a bitbucket pipeline, or manually, and then build / deploy the dockerfile with no issues. :)

**Comment by KodeStar** [comment]
You probably don't need `touch public/.nojekyll # Not sure if this is needed` as that is used to bypass the Jekyll processing GitHib pages does by default.

Also why are you running it twice?

```
npm run deploy --prefix site

# Move things around
mv public '1.0'
mkdir public
mv ./1.0 ./public/

# Setup root dir
cp -a process/. public/1.0/
echo '1.0' > public/versions.txt
echo '<meta http-equiv="refresh" content="0; url=./1.0/">' > public/index.html
touch public/.nojekyll # Not sure if this is needed

# Cleanup
rm -rf process
```

Is in there twice with no changes.

Otherwise I'm glad you got something working for you :)

**Comment by GadgetGeekNI** [comment]
You're right, I think I accidentally pasted it in twice! (edited and fixed)

Anyway. Thank you for your guidance and hopefully this helps anyone else in a similar use case to myself.

**Comment by GolDNenex** [comment]
Thanks for sharing.
