### ISSUE TITLE
Image file/image_src as URL instead of img.

### ISSUE THREAD

**Issue by GadgetGeekNI** [kasmtech/workspaces_registry_template#3]
Hi! 

I was wanting to see if there's any known issues using a URL as the image src for a workspace json entry? 

I am trying it and it seems to append the full URL of my registry to the URL of the image URL. 

When I go my Registry URL, initially the image link appears broken.

![image](https://github.com/kasmtech/workspaces_registry_template/assets/64256007/6860481e-3a12-4f1d-8fa1-4959ae6c8d93)

But when I click into the workspace definition, it works!

![image](https://github.com/kasmtech/workspaces_registry_template/assets/64256007/2c33879e-3e2f-4901-960a-7611f3d08061)

My use case is that i have a private and a public facing load balancer, due to traffic control policies Kasm has no access to my public load balancer so it can't pull down the images in the web app GUI as they're trying to pull from the URL of the private load balancer in the web app.

![image](https://github.com/kasmtech/workspaces_registry_template/assets/64256007/c82e9693-61a9-4bb6-bdf2-3c8532895d4a)

**Comment by KodeStar** [comment]
Yeah, I guess that doesn't currently work. IIRC if it's an official image it uses `/img/thumbnails/` as the base url, otherwise it uses the config.list_url + schema version. The only possible work around I can think at the moment is maybe have a folder that has public access, so something like `https://private.com/1.0/` is blocked, but `https://private.com/1.0/icons/` isn't. Not ideal, I know. 

The other thing to bare in mind is if you have your quality settings set to lossless (disabled by default) then external images wont work either as Lossless requires cross-origin isolation, which blocks requests on the page to all external sites.

**Comment by GadgetGeekNI** [comment]
Thanks for the advice!
